package com.xm.mapper;

import com.xm.model.GoodsDetail;
import com.xm.model.GoodsDetailExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface GoodsDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_detail
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    int countByExample(GoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_detail
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    int deleteByExample(GoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_detail
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    int deleteByPrimaryKey(Integer goodsDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_detail
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    int insert(GoodsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_detail
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    int insertSelective(GoodsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_detail
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    List<GoodsDetail> selectByExample(GoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_detail
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    GoodsDetail selectByPrimaryKey(Integer goodsDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_detail
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") GoodsDetail record, @Param("example") GoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_detail
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    int updateByExample(@Param("record") GoodsDetail record, @Param("example") GoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_detail
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    int updateByPrimaryKeySelective(GoodsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_detail
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    int updateByPrimaryKey(GoodsDetail record);
}