package com.xm.mapper;

import com.xm.model.LoOrderDetail;
import com.xm.model.LoOrderDetailExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface LoOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order_detail
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int countByExample(LoOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order_detail
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int deleteByExample(LoOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order_detail
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int deleteByPrimaryKey(Integer orderDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order_detail
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int insert(LoOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order_detail
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int insertSelective(LoOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order_detail
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    List<LoOrderDetail> selectByExample(LoOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order_detail
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    LoOrderDetail selectByPrimaryKey(Integer orderDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order_detail
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int updateByExampleSelective(@Param("record") LoOrderDetail record, @Param("example") LoOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order_detail
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int updateByExample(@Param("record") LoOrderDetail record, @Param("example") LoOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order_detail
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int updateByPrimaryKeySelective(LoOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order_detail
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int updateByPrimaryKey(LoOrderDetail record);
}