package com.xm.mapper;

import com.xm.model.LoShopCart;
import com.xm.model.LoShopCartExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface LoShopCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_shop_cart
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    int countByExample(LoShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_shop_cart
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    int deleteByExample(LoShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_shop_cart
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    int deleteByPrimaryKey(Integer shopCartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_shop_cart
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    int insert(LoShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_shop_cart
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    int insertSelective(LoShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_shop_cart
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    List<LoShopCart> selectByExample(LoShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_shop_cart
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    LoShopCart selectByPrimaryKey(Integer shopCartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_shop_cart
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") LoShopCart record, @Param("example") LoShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_shop_cart
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    int updateByExample(@Param("record") LoShopCart record, @Param("example") LoShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_shop_cart
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    int updateByPrimaryKeySelective(LoShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_shop_cart
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    int updateByPrimaryKey(LoShopCart record);
}