package com.xm.mapper;

import com.xm.model.LoTurnPlay;
import com.xm.model.LoTurnPlayExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface LoTurnPlayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_turn_play
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int countByExample(LoTurnPlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_turn_play
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int deleteByExample(LoTurnPlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_turn_play
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int deleteByPrimaryKey(Integer palyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_turn_play
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int insert(LoTurnPlay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_turn_play
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int insertSelective(LoTurnPlay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_turn_play
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    List<LoTurnPlay> selectByExample(LoTurnPlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_turn_play
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    LoTurnPlay selectByPrimaryKey(Integer palyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_turn_play
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int updateByExampleSelective(@Param("record") LoTurnPlay record, @Param("example") LoTurnPlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_turn_play
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int updateByExample(@Param("record") LoTurnPlay record, @Param("example") LoTurnPlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_turn_play
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int updateByPrimaryKeySelective(LoTurnPlay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_turn_play
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int updateByPrimaryKey(LoTurnPlay record);
}