package com.xm.mapper;

import com.xm.model.PurSysMenu;
import com.xm.model.PurSysMenuExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PurSysMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_menu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int countByExample(PurSysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_menu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int deleteByExample(PurSysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_menu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int deleteByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_menu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int insert(PurSysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_menu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int insertSelective(PurSysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_menu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    List<PurSysMenu> selectByExample(PurSysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_menu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    PurSysMenu selectByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_menu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int updateByExampleSelective(@Param("record") PurSysMenu record, @Param("example") PurSysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_menu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int updateByExample(@Param("record") PurSysMenu record, @Param("example") PurSysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_menu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int updateByPrimaryKeySelective(PurSysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_menu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int updateByPrimaryKey(PurSysMenu record);
}