package com.xm.mapper;

import com.xm.model.PurSysUser;
import com.xm.model.PurSysUserExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PurSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_user
     *
     * @mbggenerated Sun Aug 12 18:01:38 CST 2018
     */
    int countByExample(PurSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_user
     *
     * @mbggenerated Sun Aug 12 18:01:38 CST 2018
     */
    int deleteByExample(PurSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_user
     *
     * @mbggenerated Sun Aug 12 18:01:38 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_user
     *
     * @mbggenerated Sun Aug 12 18:01:38 CST 2018
     */
    int insert(PurSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_user
     *
     * @mbggenerated Sun Aug 12 18:01:38 CST 2018
     */
    int insertSelective(PurSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_user
     *
     * @mbggenerated Sun Aug 12 18:01:38 CST 2018
     */
    List<PurSysUser> selectByExample(PurSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_user
     *
     * @mbggenerated Sun Aug 12 18:01:38 CST 2018
     */
    PurSysUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_user
     *
     * @mbggenerated Sun Aug 12 18:01:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") PurSysUser record, @Param("example") PurSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_user
     *
     * @mbggenerated Sun Aug 12 18:01:38 CST 2018
     */
    int updateByExample(@Param("record") PurSysUser record, @Param("example") PurSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_user
     *
     * @mbggenerated Sun Aug 12 18:01:38 CST 2018
     */
    int updateByPrimaryKeySelective(PurSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_user
     *
     * @mbggenerated Sun Aug 12 18:01:38 CST 2018
     */
    int updateByPrimaryKey(PurSysUser record);
    
    List<String> selectUserPermissions(String userId);
}