package com.xm.mapper;

import com.xm.model.PurSysRole;
import com.xm.model.PurSysRoleExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PurSysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_role
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int countByExample(PurSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_role
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int deleteByExample(PurSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_role
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_role
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int insert(PurSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_role
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int insertSelective(PurSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_role
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    List<PurSysRole> selectByExample(PurSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_role
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    PurSysRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_role
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int updateByExampleSelective(@Param("record") PurSysRole record, @Param("example") PurSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_role
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int updateByExample(@Param("record") PurSysRole record, @Param("example") PurSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_role
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int updateByPrimaryKeySelective(PurSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_role
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int updateByPrimaryKey(PurSysRole record);
}