package com.xm.mapper;

import com.xm.model.SysDatabase;
import com.xm.model.SysDatabaseExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SysDatabaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_database
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    int countByExample(SysDatabaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_database
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    int deleteByExample(SysDatabaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_database
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    int deleteByPrimaryKey(Integer baseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_database
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    int insert(SysDatabase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_database
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    int insertSelective(SysDatabase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_database
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    List<SysDatabase> selectByExample(SysDatabaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_database
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    SysDatabase selectByPrimaryKey(Integer baseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_database
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysDatabase record, @Param("example") SysDatabaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_database
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    int updateByExample(@Param("record") SysDatabase record, @Param("example") SysDatabaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_database
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    int updateByPrimaryKeySelective(SysDatabase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_database
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    int updateByPrimaryKey(SysDatabase record);
}