package com.xm.model;

public class LoShopCart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_shop_cart.shop_cart_id
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    private Integer shopCartId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_shop_cart.goods_id
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_shop_cart.user_id
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_shop_cart.num
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_shop_cart.is_check
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    private Boolean isCheck;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_shop_cart.shop_cart_id
     *
     * @return the value of lo_shop_cart.shop_cart_id
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    public Integer getShopCartId() {
        return shopCartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_shop_cart.shop_cart_id
     *
     * @param shopCartId the value for lo_shop_cart.shop_cart_id
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    public void setShopCartId(Integer shopCartId) {
        this.shopCartId = shopCartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_shop_cart.goods_id
     *
     * @return the value of lo_shop_cart.goods_id
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_shop_cart.goods_id
     *
     * @param goodsId the value for lo_shop_cart.goods_id
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_shop_cart.user_id
     *
     * @return the value of lo_shop_cart.user_id
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_shop_cart.user_id
     *
     * @param userId the value for lo_shop_cart.user_id
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_shop_cart.num
     *
     * @return the value of lo_shop_cart.num
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_shop_cart.num
     *
     * @param num the value for lo_shop_cart.num
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_shop_cart.is_check
     *
     * @return the value of lo_shop_cart.is_check
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    public Boolean getIsCheck() {
        return isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_shop_cart.is_check
     *
     * @param isCheck the value for lo_shop_cart.is_check
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    public void setIsCheck(Boolean isCheck) {
        this.isCheck = isCheck;
    }
}