package com.xm.model;

public class LoTurnPlay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_turn_play.paly_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private Integer palyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_turn_play.attachment_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private Integer attachmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_turn_play.status
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_turn_play.sort
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_turn_play.is_eabled
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private Boolean isEabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_turn_play.link
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private String link;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_turn_play.paly_id
     *
     * @return the value of lo_turn_play.paly_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public Integer getPalyId() {
        return palyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_turn_play.paly_id
     *
     * @param palyId the value for lo_turn_play.paly_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setPalyId(Integer palyId) {
        this.palyId = palyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_turn_play.attachment_id
     *
     * @return the value of lo_turn_play.attachment_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public Integer getAttachmentId() {
        return attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_turn_play.attachment_id
     *
     * @param attachmentId the value for lo_turn_play.attachment_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setAttachmentId(Integer attachmentId) {
        this.attachmentId = attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_turn_play.status
     *
     * @return the value of lo_turn_play.status
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_turn_play.status
     *
     * @param status the value for lo_turn_play.status
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_turn_play.sort
     *
     * @return the value of lo_turn_play.sort
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_turn_play.sort
     *
     * @param sort the value for lo_turn_play.sort
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_turn_play.is_eabled
     *
     * @return the value of lo_turn_play.is_eabled
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public Boolean getIsEabled() {
        return isEabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_turn_play.is_eabled
     *
     * @param isEabled the value for lo_turn_play.is_eabled
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setIsEabled(Boolean isEabled) {
        this.isEabled = isEabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_turn_play.link
     *
     * @return the value of lo_turn_play.link
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_turn_play.link
     *
     * @param link the value for lo_turn_play.link
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }
}