package com.xm.model;

public class PurSysRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_sys_role.id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_sys_role.name
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_sys_role.detail
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_sys_role.id
     *
     * @return the value of pur_sys_role.id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_sys_role.id
     *
     * @param id the value for pur_sys_role.id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_sys_role.name
     *
     * @return the value of pur_sys_role.name
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_sys_role.name
     *
     * @param name the value for pur_sys_role.name
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_sys_role.detail
     *
     * @return the value of pur_sys_role.detail
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_sys_role.detail
     *
     * @param detail the value for pur_sys_role.detail
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}