package com.xm.model;

public class PurSysUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_sys_user_role.id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_sys_user_role.user_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_sys_user_role.role_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_sys_user_role.id
     *
     * @return the value of pur_sys_user_role.id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_sys_user_role.id
     *
     * @param id the value for pur_sys_user_role.id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_sys_user_role.user_id
     *
     * @return the value of pur_sys_user_role.user_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_sys_user_role.user_id
     *
     * @param userId the value for pur_sys_user_role.user_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_sys_user_role.role_id
     *
     * @return the value of pur_sys_user_role.role_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_sys_user_role.role_id
     *
     * @param roleId the value for pur_sys_user_role.role_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}