package com.xm.model;

import java.util.Date;

public class SysDatabase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_database.base_id
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    private Integer baseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_database.type
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_database.code
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_database.value
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_database.remark
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_database.create_time
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_database.user_id
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_database.sort
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_database.base_id
     *
     * @return the value of sys_database.base_id
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    public Integer getBaseId() {
        return baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_database.base_id
     *
     * @param baseId the value for sys_database.base_id
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    public void setBaseId(Integer baseId) {
        this.baseId = baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_database.type
     *
     * @return the value of sys_database.type
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_database.type
     *
     * @param type the value for sys_database.type
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_database.code
     *
     * @return the value of sys_database.code
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_database.code
     *
     * @param code the value for sys_database.code
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_database.value
     *
     * @return the value of sys_database.value
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_database.value
     *
     * @param value the value for sys_database.value
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_database.remark
     *
     * @return the value of sys_database.remark
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_database.remark
     *
     * @param remark the value for sys_database.remark
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_database.create_time
     *
     * @return the value of sys_database.create_time
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_database.create_time
     *
     * @param createTime the value for sys_database.create_time
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_database.user_id
     *
     * @return the value of sys_database.user_id
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_database.user_id
     *
     * @param userId the value for sys_database.user_id
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_database.sort
     *
     * @return the value of sys_database.sort
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_database.sort
     *
     * @param sort the value for sys_database.sort
     *
     * @mbggenerated Sun Aug 12 17:16:38 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}