package com.xm.mapper;

import com.xm.model.LoGoods;
import com.xm.model.LoGoodsExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface LoGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_goods
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    int countByExample(LoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_goods
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    int deleteByExample(LoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_goods
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    int deleteByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_goods
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    int insert(LoGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_goods
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    int insertSelective(LoGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_goods
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    List<LoGoods> selectByExample(LoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_goods
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    LoGoods selectByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_goods
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") LoGoods record, @Param("example") LoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_goods
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    int updateByExample(@Param("record") LoGoods record, @Param("example") LoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_goods
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    int updateByPrimaryKeySelective(LoGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_goods
     *
     * @mbggenerated Sun Aug 12 16:07:24 CST 2018
     */
    int updateByPrimaryKey(LoGoods record);
}