package com.xm.mapper;

import com.xm.model.LoOrder;
import com.xm.model.LoOrderExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface LoOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order
     *
     * @mbggenerated Sat Aug 11 10:55:45 CST 2018
     */
    int countByExample(LoOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order
     *
     * @mbggenerated Sat Aug 11 10:55:45 CST 2018
     */
    int deleteByExample(LoOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order
     *
     * @mbggenerated Sat Aug 11 10:55:45 CST 2018
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order
     *
     * @mbggenerated Sat Aug 11 10:55:45 CST 2018
     */
    int insert(LoOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order
     *
     * @mbggenerated Sat Aug 11 10:55:45 CST 2018
     */
    int insertSelective(LoOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order
     *
     * @mbggenerated Sat Aug 11 10:55:45 CST 2018
     */
    List<LoOrder> selectByExample(LoOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order
     *
     * @mbggenerated Sat Aug 11 10:55:45 CST 2018
     */
    LoOrder selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order
     *
     * @mbggenerated Sat Aug 11 10:55:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") LoOrder record, @Param("example") LoOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order
     *
     * @mbggenerated Sat Aug 11 10:55:45 CST 2018
     */
    int updateByExample(@Param("record") LoOrder record, @Param("example") LoOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order
     *
     * @mbggenerated Sat Aug 11 10:55:45 CST 2018
     */
    int updateByPrimaryKeySelective(LoOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_order
     *
     * @mbggenerated Sat Aug 11 10:55:45 CST 2018
     */
    int updateByPrimaryKey(LoOrder record);
}