package com.xm.mapper;

import com.xm.model.PurSysRolemenu;
import com.xm.model.PurSysRolemenuExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PurSysRolemenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_rolemenu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int countByExample(PurSysRolemenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_rolemenu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int deleteByExample(PurSysRolemenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_rolemenu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_rolemenu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int insert(PurSysRolemenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_rolemenu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int insertSelective(PurSysRolemenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_rolemenu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    List<PurSysRolemenu> selectByExample(PurSysRolemenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_rolemenu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    PurSysRolemenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_rolemenu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int updateByExampleSelective(@Param("record") PurSysRolemenu record, @Param("example") PurSysRolemenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_rolemenu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int updateByExample(@Param("record") PurSysRolemenu record, @Param("example") PurSysRolemenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_rolemenu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int updateByPrimaryKeySelective(PurSysRolemenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_sys_rolemenu
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    int updateByPrimaryKey(PurSysRolemenu record);
}