package com.xm.model;

import java.util.Date;

public class GoodsDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_detail.goods_detail_id
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    private Integer goodsDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_detail.goods_id
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_detail.attachment_id
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    private Integer attachmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_detail.remark
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_detail.isdeleted
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    private Boolean isdeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_detail.title
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_detail.create_time
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_detail.goods_detail_id
     *
     * @return the value of goods_detail.goods_detail_id
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    public Integer getGoodsDetailId() {
        return goodsDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_detail.goods_detail_id
     *
     * @param goodsDetailId the value for goods_detail.goods_detail_id
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    public void setGoodsDetailId(Integer goodsDetailId) {
        this.goodsDetailId = goodsDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_detail.goods_id
     *
     * @return the value of goods_detail.goods_id
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_detail.goods_id
     *
     * @param goodsId the value for goods_detail.goods_id
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_detail.attachment_id
     *
     * @return the value of goods_detail.attachment_id
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    public Integer getAttachmentId() {
        return attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_detail.attachment_id
     *
     * @param attachmentId the value for goods_detail.attachment_id
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    public void setAttachmentId(Integer attachmentId) {
        this.attachmentId = attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_detail.remark
     *
     * @return the value of goods_detail.remark
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_detail.remark
     *
     * @param remark the value for goods_detail.remark
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_detail.isdeleted
     *
     * @return the value of goods_detail.isdeleted
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    public Boolean getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_detail.isdeleted
     *
     * @param isdeleted the value for goods_detail.isdeleted
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_detail.title
     *
     * @return the value of goods_detail.title
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_detail.title
     *
     * @param title the value for goods_detail.title
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_detail.create_time
     *
     * @return the value of goods_detail.create_time
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_detail.create_time
     *
     * @param createTime the value for goods_detail.create_time
     *
     * @mbggenerated Sat Aug 11 16:08:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}