package com.xm.model;

public class LoOrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_order_detail.order_detail_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private Integer orderDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_order_detail.order_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_order_detail.goods_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_order_detail.number
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_order_detail.remark
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_order_detail.order_detail_id
     *
     * @return the value of lo_order_detail.order_detail_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public Integer getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_order_detail.order_detail_id
     *
     * @param orderDetailId the value for lo_order_detail.order_detail_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setOrderDetailId(Integer orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_order_detail.order_id
     *
     * @return the value of lo_order_detail.order_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_order_detail.order_id
     *
     * @param orderId the value for lo_order_detail.order_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_order_detail.goods_id
     *
     * @return the value of lo_order_detail.goods_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_order_detail.goods_id
     *
     * @param goodsId the value for lo_order_detail.goods_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_order_detail.number
     *
     * @return the value of lo_order_detail.number
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_order_detail.number
     *
     * @param number the value for lo_order_detail.number
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_order_detail.remark
     *
     * @return the value of lo_order_detail.remark
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_order_detail.remark
     *
     * @param remark the value for lo_order_detail.remark
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}