package com.xm.model;

public class PurSysMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_sys_menu.menu_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_sys_menu.parent_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_sys_menu.code
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_sys_menu.full_name
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_sys_menu.description
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_sys_menu.enabled
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private Integer enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_sys_menu.sort
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_sys_menu.menu_id
     *
     * @return the value of pur_sys_menu.menu_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_sys_menu.menu_id
     *
     * @param menuId the value for pur_sys_menu.menu_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_sys_menu.parent_id
     *
     * @return the value of pur_sys_menu.parent_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_sys_menu.parent_id
     *
     * @param parentId the value for pur_sys_menu.parent_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_sys_menu.code
     *
     * @return the value of pur_sys_menu.code
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_sys_menu.code
     *
     * @param code the value for pur_sys_menu.code
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_sys_menu.full_name
     *
     * @return the value of pur_sys_menu.full_name
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_sys_menu.full_name
     *
     * @param fullName the value for pur_sys_menu.full_name
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_sys_menu.description
     *
     * @return the value of pur_sys_menu.description
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_sys_menu.description
     *
     * @param description the value for pur_sys_menu.description
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_sys_menu.enabled
     *
     * @return the value of pur_sys_menu.enabled
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_sys_menu.enabled
     *
     * @param enabled the value for pur_sys_menu.enabled
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_sys_menu.sort
     *
     * @return the value of pur_sys_menu.sort
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_sys_menu.sort
     *
     * @param sort the value for pur_sys_menu.sort
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}