package com.xm.model;

public class PurSysRolemenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_sys_rolemenu.id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_sys_rolemenu.role_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_sys_rolemenu.menu_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    private Integer menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_sys_rolemenu.id
     *
     * @return the value of pur_sys_rolemenu.id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_sys_rolemenu.id
     *
     * @param id the value for pur_sys_rolemenu.id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_sys_rolemenu.role_id
     *
     * @return the value of pur_sys_rolemenu.role_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_sys_rolemenu.role_id
     *
     * @param roleId the value for pur_sys_rolemenu.role_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_sys_rolemenu.menu_id
     *
     * @return the value of pur_sys_rolemenu.menu_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_sys_rolemenu.menu_id
     *
     * @param menuId the value for pur_sys_rolemenu.menu_id
     *
     * @mbggenerated Sat Aug 11 10:55:46 CST 2018
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
}